### ISSUE TITLE
Prevent package installation under Atom 1.34

### ISSUE THREAD

**Issue by softwarecreations** [xavierfoucrier/atom-soft-tabs-length#16]
But I upgraded to 1.38.2 and it's working beautifully!

Thank you for sharing this!!!

**Comment by xavierfoucrier** [comment]
Hi @softwarecreations,

Thanks for your report. Unfortunately, the package has been developed on **Atom 1.34+** so there are probably some differences between the 1.27 and 1.38 API.

I will update the package to avoid this kind of issue.

Anyway, hope you enjoy the package and don't hesitate to get back if you have any idea that could be implemented in the future.

:v:
