### ISSUE TITLE
Use of a global .editorconfig file

### ISSUE THREAD

**Issue by softwarecreations** [xavierfoucrier/atom-soft-tabs-length#17]
This is a great project, using `.editorconfig` is a great solution for collaboration.

The reason I found this project is because I work in different languages that need different levels of indentation to be readable. I can comfortably read C-like, JSON or XML languages with 1 space indentation. But then BASIC style languages need an indentation of 4 spaces in my opinion.

So my need for custom indentation is currently not project specific, but I expect this functionality will become very useful to me in future. My need for custom indentation is currently filetype specific, regardless of the project.

I had never come across the `.editorconfig` standard before finding this plugin and I think it's really nice how it supports distinct indentation settings per filetype within a project.

**I think it would be great to have a default `.editorconfig` that, in the absence of a project specific `.editorconfig`, is evaluated for all files.**

That way it's not necessary to create a .editorconfig for every personal project (which I have a lot of). But rather it will only be necessary to create one of these files for collaborative projects.

currently my `.editorconfig` looks like this
```
root = true
[*.au3]

indent_style = space
indent_size = 4

```
So it only sets custom indentation for au3 files. Every other file uses my atom default settings.

--------------------

Fun-fact:
I originally used 2 spaces as my default indentation level, but then I found this amazing plugin: `toggle-quotes` with a setting of

```
"'`
```
works very nicely for javascript files. But it had a bug where it only worked on files with a tab indentation of 1. So I got used to using a tab indentation of 1. I see the bug has been fixed now, so I might go back to 2 spaces some time.

**Comment by xavierfoucrier** [comment]
Hi @softwarecreations,

Did you mean a **"global"** `.editorconfig` by "default"?

**Comment by softwarecreations** [comment]
> Did you mean a **"global"** `.editorconfig` by "default"?

Yes, so for example I could have a file  ~/development/.editorconfig and specify that file in the plugin settings as my global .editorconfig.
In that file I can set my preferences for each filetype. Then only if I need to override those preferences, I create a .editorconfig in a project folder.

That's the idea

**Comment by xavierfoucrier** [comment]
@softwarecreations thanks for the precision.
I will mark this as a feature request :wink:

**Comment by xavierfoucrier** [comment]
Hi @softwarecreations,

After a bunch of tests adding this feature, `atom-soft-tabs-length` require that the Atom `EditorConfig` package detect an `.editorconfig` file to properly work. You can't specify a global `.editorconfig` file whenever you want on your machine, **it must be inside the project directory or inside one of the parent directory of your project**.

If no `.editorconfig` file is detected by the Atom `EditorConfig` package, the indentation stay the same in the editor and `atom-soft-tabs-length` will not properly work...

The short solution for that is to put your global `.editorconfig` file at the root of your development directory, so that it will be properly parse by the Atom `EditorConfig` package: and `atom-soft-tabs-length` will be able to adjust the soft tabs:

```
/development
  /project-a
  /project-b
  /project-c
  .editorconfig
```

> Note that you can override this **global configuration** by adding an `.editorconfig` file at the root of other project directories

Please let me know if it works for you :v: :wink:

**Comment by softwarecreations** [comment]
@xavierfoucrier that sounds great buddy, thank you.

Will your example with `.editorconfig` in `/development` work even if I open `/project-a` as my project directory?
I like to have one atom instance per project. Like this
![image](https://user-images.githubusercontent.com/28704571/67939730-d9fa1b80-fbda-11e9-9edc-1dcfccd442b2.png)

Not like this
![image](https://user-images.githubusercontent.com/28704571/67939743-e0889300-fbda-11e9-8053-1075a461dbff.png)

So if `project-a` is my root project dir that I've opened, will it still find .editorconfig that's in a higher dir?

EDIT I got a notification of your reply to this message in this thread by email but it seems you've deleted it?

**Comment by xavierfoucrier** [comment]
Hi @softwarecreations,

Of course it works as the Atom EditorConfig package is **travelling the file system**, not the editor project tree.

I am using the [`editorconfig`](https://www.npmjs.com/package/editorconfig) package and as specified in the documentation, it will search for the config file from the current directory - _in fact the project directory opened in Atom_ - to the root directory - _`/` by default, your file system root directory_.

In theory you could place the config file at the root of your disk and the package will find it. :wink:

**Comment by xavierfoucrier** [comment]
Hi @softwarecreations,

Of course it will work as the Atom EditorConfig package is **travelling the file system**, not the editor project tree.

I am using the [`editorconfig`](https://www.npmjs.com/package/editorconfig) package and as specified in the documentation, it will search for the config file from the current directory - _in fact the project directory opened in Atom_ - to the root directory - _`/` by default, your file system root directory_.

In theory you could place the config file at the root of your disk and the package will find it. :wink: 

EDIT: yeah that was edited by me just now :smile: :
I need to **upgrade the internal code of the plugin** to make it properly work

**Comment by softwarecreations** [comment]
Very nice, thank you. Feel free to close the issue when you're ready :)
EDIT: Oops wrong button.

**Comment by xavierfoucrier** [comment]
Hi @softwarecreations,

Its up and ready in the latest build `v0.6.0`.
Let me know if you have any trouble.

Thanks :v:
